### ISSUE TITLE
pyenv problem

### ISSUE THREAD

**Issue by piotrszymanek** [Derfirm/pornhub-api#392]
I have installed it under pyenv.
Then I can't import module:

psrv:~/python/ph$ python
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pornhub_api import PornhubApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ps/python/ph/lib/python3.10/site-packages/pornhub_api/__init__.py", line 1, in <module>
    from pornhub_api.api import PornhubApi
  File "/home/ps/python/ph/lib/python3.10/site-packages/pornhub_api/api.py", line 2, in <module>
    from pornhub_api.modules.video import Video
  File "/home/ps/python/ph/lib/python3.10/site-packages/pornhub_api/modules/video.py", line 6, in <module>
    from pornhub_api.schemas.video import VideoResult, IsVideoActiveResult
  File "/home/ps/python/ph/lib/python3.10/site-packages/pornhub_api/schemas/video.py", line 41, in <module>
    class VideoResult(BaseModel):
  File "/home/ps/python/ph/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 115, in __new__
    private_attributes = inspect_namespace(
  File "/home/ps/python/ph/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 371, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'

**Comment by Derfirm** [comment]
@piotrszymanek thank you for reporting, this is related to incorrect pydantic pinning
should be fixed in version 0.4.0

**Comment by piotrszymanek** [comment]
Thank you, I confirm that now it is working.
