### ISSUE TITLE
decoder error

### ISSUE THREAD

**Issue by AhmadNaruto** [Derfirm/pornhub-api#9]
What about with this error

Traceback (most recent call last):
  File "ph.py", line 7, in <module>
    tags = random.sample(api.video.tags("f").tags, 5)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pornhub_api/modules/video.py", line 45, in tags
    return self.backend.send_request(
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/pornhub_api/backends/requests.py", line 12, in send_request
    data = response.json()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AhmadNaruto** [comment]
has solved

**Comment by AhmadNaruto** [comment]
6
